apiVersion: apps/v1
kind: Deployment
metadata:
  name: hameddeployment
  namespace: hamedns
  annotations:
    kubernetes.io/change-cause: "second deployment"
spec:
  replicas: 10
  selector:
    matchLabels:
      app: mynginxapp
  template:
    metadata:
      labels:
        app: mynginxapp
        type: frontend
    spec:
      containers:
      - name: hamednginx
        image: repo.ficld.ir/library/nginx:1.21.1
        resources:
          limits:
            memory: "50M"
            cpu: "20m"
          requests:
            memory: "10M"
            cpu: "10m"
