apiVersion: v1
kind: Pod
metadata:
  name: initcontaierexample
  namespace: hamedns
  labels:
    name: initcontaierexample
spec:
  volumes:
    - name: myvol-1
      emptyDir:
        sizeLimit: 100M
  initContainers:
    - name: myconfigs
      image: repo.ficld.ir/library/busybox:1.32.0
      command:
        - "sh"
        - "-c"
        - |
          echo "At $(data) your configs generated" > /mnt/vol/init1
          sleep 5
      volumeMounts:
        - name: myvol-1
          mountPath: /mnt/vol
      resources:
        requests:
          memory: "10Mi"
          cpu: "100m"
    - name: git-clonner
      image: repo.ficld.ir/library/busybox:1.32.0
      command:
        - "sh"
        - "-c"
        - |
          echo "At $(date) your git clonned" > /mnt/vol/init2
      volumeMounts:
        - name: myvol-1
          mountPath: /mnt/vol
      resources:
        requests:
          memory: "10Mi"
          cpu: "100m"
  containers:
  - name: mywebserver
    image: repo.ficld.ir/library/nginx:1.21.1
    resources:
      requests:
        memory: "10Mi"
        cpu: "100m"
      limits:
        memory: "100Mi"
        cpu: "700m"
    ports:
      - containerPort: 80
    volumeMounts:
        - name: myvol-1
          mountPath: /mnt/vol
  - name: debbuger
    image: repo.ficld.ir/library/alpine:3.11.3
    command:
      - "sleep"
      - "infinity"
    resources:
      requests:
        memory: "10Mi"
        cpu: "100m"
      limits:
        memory: "100Mi"
        cpu: "700m"
    ports:
      - containerPort: 8080
    volumeMounts:
        - name: myvol-1
          mountPath: /mnt/vol
