apiVersion: v1
kind: ReplicationController
metadata:
  name: mysecondapp
spec:
  replicas: 3
  selector:
    app: mysecondapp
  template:
    metadata:
      name: mysecondapp
      labels:
        app: mysecondapp
    spec:
      containers:
        - name: mysecondapp
          image: repo.ficld.ir/library/nginx:latest
          ports:
            - containerPort: 8080
              hostPort: 8090
